apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rapidast-integration-test
spec:
  params:
    # this SNAPSHOT should be produced by the build pipeline and contain the containerImage we want to test with rapidast
    - name: SNAPSHOT
      type: string
  tasks:
    # Create an ephemeral namespace where we will deploy our application.
    - name: provision-env
      taskRef:
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1@sha256:8a344ed61dfeabf741f3f08892414f223ade1849f995da0db172e79c4afc21a3
          - name: kind
            value: task
        resolver: bundles
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)

    # Deploy the snapshot image into the new environment.
    - name: deploy-app
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      runAfter:
      - provision-env
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        volumes:
          # A volume which persists for the lifetime of the pipeline and is
          # shared across steps.
          - name: scratch
            emptyDir: {}
        steps:
          # Write the kubeconfig to a volume we can use in subsequent steps.
          - name: get-kubeconfig
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: KUBECONFIG
                value: /scratch/kubeconfig.yml
              - name: KUBECONFIG_VALUE
                valueFrom:
                  secretKeyRef:
                    name: "$(tasks.provision-env.results.secretRef)"
                    key: kubeconfig
            volumeMounts:
              - name: scratch
                mountPath: /scratch
            script: |
              #!/bin/bash
              set -euxo pipefail

              cat <<< "$KUBECONFIG_VALUE" > "$KUBECONFIG"
              echo "Wrote kubeconfig for new environment to $KUBECONFIG"

          # Deploy an instance of our application using the snapshot image.
          - name: deploy-app
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: KUBECONFIG
                value: /scratch/kubeconfig.yml
            volumeMounts:
              - name: scratch
                mountPath: /scratch
            script: |
              #!/bin/bash
              set -euxo pipefail

              IMAGE=$(echo "$SNAPSHOT" | jq -r '.components[0].containerImage')
              echo "Extracted image: $IMAGE"

              mkdir /scratch/manifests

              cat <<EOF > /scratch/manifests/00-prometheus.yaml
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: prometheus-config
              data:
                rules.yaml: |
                  groups:
                  - name: test
                    rules:
                    - alert: Test
                      expr: vector(1)
                prometheus.yaml: |
                  global:
                    scrape_interval: 5s
                  scrape_configs:
                  - job_name: prometheus
                    static_configs:
                    - targets: ["localhost:9090"]
                  rule_files: [rules.yaml]
              ---
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: prometheus
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app.kubernetes.io/name: prometheus
                template:
                  metadata:
                    labels:
                      app.kubernetes.io/name: prometheus
                  spec:
                    containers:
                    - args:
                      - --config.file=/config/prometheus.yaml
                      - --web.enable-remote-write-receiver
                      ports:
                      - containerPort: 9090
                        name: http
                      image: quay.io/prometheus/prometheus:v3.8.1
                      name: prometheus
                      volumeMounts:
                      - name: config
                        mountPath: /config
                      - name: prometheus
                        mountPath: /prometheus
                    volumes:
                    - configMap:
                        name: prometheus-config
                      name: config
                    - emptyDir: {}
                      name: prometheus
              ---
              apiVersion: v1
              kind: Service
              metadata:
                name: prometheus
              spec:
                ports:
                - name: http
                  port: 9090
                  portName: http
              EOF

              cat <<EOF > /scratch/manifests/01-observatorium-api.yaml
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: observatorium-api-config
              data:
                rbac.yaml: |
                  roles:
                  - name: read-write
                    resources:
                    - metrics
                    tenants:
                    - test
                    permissions:
                    - read
                    - write
                  roleBindings:
                  - name: test
                    roles:
                    - read-write
                    subjects:
                    - kind: user
                      name: anonymous
                tenants.yaml: |
                  tenants:
                  - name: test
                    id: 00000000-0000-0000-0000-000000000000
                    authenticator:
                      type: anonymous
                      config: {}
              ---
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: observatorium-api
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app.kubernetes.io/name: observatorium-api
                template:
                  metadata:
                    labels:
                      app.kubernetes.io/name: observatorium-api
                  spec:
                    containers:
                    - args:
                      - -metrics.read.endpoint=http://example.com/
                      - -metrics.write.endpoint=http://example.com/
                      - -rbac.config=/config/rbac.yaml
                      - -tenants.config=/config/tenants.yaml
                      ports:
                      - containerPort: 8080
                        name: http
                      env:
                      - name: INSECURE_ANONYMOUS_AUTHENTICATOR_ENABLED
                        value: "1"
                      image: $IMAGE
                      name: observatorium-api
                      volumeMounts:
                      - name: config
                        mountPath: /config
                    volumes:
                    - configMap:
                        name: observatorium-api-config
                      name: config
              ---
              apiVersion: v1
              kind: Service
              metadata:
                name: observatorium-api
              spec:
                ports:
                - name: http
                  port: 8080
                  portName: http
              EOF

              echo "Applying manifests..."
              oc apply -f /scratch/manifests/

              echo "Waiting for deployments to be ready..."
              oc wait --for=condition=Available=true deployment/prometheus --timeout=120s
              oc wait --for=condition=Available=true deployment/observatorium-api --timeout=120s
              oc get pods
              oc logs deployments/prometheus
              oc logs deployments/observatorium-api

    # Run the scanner.
    - name: rapidast-check
      runAfter:
      - deploy-app
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhatproductsecurity/rapidast
          - name: revision
            value: "0119197b4c18791b0947a12a449068f2b718e18c"
          - name: pathInRepo
            value: examples/konflux/rapidast-check.yaml
      params:
        - name: KUBECONFIG_SECRET
          value: "$(tasks.provision-env.results.secretRef)"
        - name: PORT_FORWARD_TARGETS
          value: "deployment/observatorium-api 8080:8080"
        - name: RAPIDAST_CONFIG_VALUE
          value: |
            config:
              configVersion: 6

            application:
              shortName: rhobs-observatorium-api-main
              url: http://127.0.0.1:8080

            scanners:
              zap:
                apiScan:
                  target: http://127.0.0.1:8080
                  apis:
                    apiUrl: http://127.0.0.1:8080/openapi.yaml
                passiveScan:
                  disabledRules: ""
